#! /usr/bin/env bash
#   _
#  | |
#  | |__  ___ _ ____      ___ __ ___  _ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#  | |_) \__ \ |_) \ V  V /| | | | | | | | (__
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#            | |
#            |_|
#
#   ~/.config/bspwm - Bspwm Configuration file

# Gap between windows
export gap=4
# Panel height
export PANEL_HEIGT=20

# This creates negative padding equal to window gap so that
# gaps are shown only between windows and not on desktop edges.
bspc config window_gap      $gap;
bspc config top_padding     $((PANEL_HEIGT-$gap))
bspc config left_padding    -$gap
bspc config right_padding   -$gap
bspc config bottom_padding  -$gap

# Various settings

# Defailt setup uses negative pagging. Gapless monovle looks really weird like that
bspc config gapless_monocle     false
bspc config borderless_monocle  true
bspc config single_monocle      false
#bspc config ignore_ewh_focus   false
#bspc config initial_polarity   second_child
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

## Honr size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints   true

## Color Settings
bspc config focused_border_color    "#585858"
bspc config normal_border_color     "#222D31"
bsps config presel_feedback_color   "#8d8f8d"
bspc config border_width 1

bspc config focus_follows_pointer true
# Some keybindings automatically enable and disavle this settings
#bspc config pointer_follow_focus true

# Settings for manual splitting
bspc config split_ratio 0.52

#bspc monitor -d          

# This creates and names desktops for multiple monitors.
workspaces_multimonitor &

# Windows and Application Rules
bspc rule -a gcolor3 state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a file-file-roller state= floating center=true
bspc rule -a spotify state=pseudo_tiled
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a firefox private=on
bspc rule -a libreoffice state=tiled

## Autostart apps
limepanel &
